//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OkulProje
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class okulllEntities : DbContext
    {
        public okulllEntities()
            : base("name=okulllEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<pru_ders> pru_ders { get; set; }
        public virtual DbSet<pru_ogrenci> pru_ogrenci { get; set; }
        public virtual DbSet<pru_ogrenciders> pru_ogrenciders { get; set; }
        public virtual DbSet<pru_okulyonetim> pru_okulyonetim { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
